NHSDigital/multicast-notification-service

azure/azure-release-pipeline.yml, manifest_template.yml
As advised by the apigee team.
=> Allow QA environments as part of build

specification/multicast-notification-service.yaml
Minor change. Previously the FHIR example event was pds-record-change, which is not the initial use case we're supporting. Instead it should be change of GP
You can view and test the change here: https://training2.nhsd.io/developer/api-catalogue/named/daniel-yip#post-/events
=> [EM-315] Amend example FHIR payload to be GP Change

specification/multicast-notification-service.yaml
=> [EM-345] Move error section

specification/multicast-notification-service.yaml
=> Changed heading size

manifest_template.yml, tests/test_endpoints.py
commenting out user-auth option for events submission
=> EM-278 commenting out user-auth option

azure/azure-release-pipeline.yml, tests/test_endpoints.py
Commented out sandbox and int test runs as different steps are required. See the results in the support channel when search for AssertionError: Could not CREATE TestApp. This is because they are associated with prod APIGEE.
We'll add robust tests under the follow-on ticket - there are some pre reqs before we begin that work.
I also tightened up a few tests.
* [] Dev
=> Fixed pipelines

azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml, azure/templates/run-tests.yml, proxies/live/apiproxy/targets/target.xml, tests/data/pds-change-of-gp-event-fhir.json, tests/data/pds-change-of-gp-event-mds.json, tests/test_endpoints.py
Links the APIGEE proxy to our target backend.
This initial PR is a quick test to check it links up so we can ping some stuff at it. Having looked at the documentation, if I've understood it correctly, we might need some minor rework to the target servers we requested
=> [EM-346] Link proxy to our backend

specification/multicast-notification-service.yaml
=> Move lightweight word to be clearer about what is lightweight

azure/azure-release-pipeline.yml
APIM Proxy repo shipped with incorrect commands for the INT environment. I've updated it to hopefully the correct one.
=> Aligned test command with the correct name

azure/azure-release-pipeline.yml, azure/templates/run-tests.yml
Needed to run the full command i.e. `make test-prod`.
Then needed to change the parameter to be referenced properly as a template string.
=> [EM-XX] Final fixes

Makefile
=> Another incorrect thing

specification/multicast-notification-service.yaml
We've completed the integration to our DEV and INT backend. This just brings the documentation up to date.
=> [EM-XX] Updated documentation now that we have an int environment

sandbox/mockEvents.js, specification/multicast-notification-service.yaml, tests/data/pds-change-of-gp-event-mds.json
Waiting on EM-363 within the event-poc repo. Don't want to update the specification until this change is locked in and merged in the backend repo.
Added patient's registered GP Practice to the MDS within the specification.
Also updated smoketests and sandbox tests to account for this.
=> [EM-363] Updated specs and tests to include Registered GP Practice

azure/azure-release-pipeline.yml
Disabled the tests for internal-qa as it does not have a backend target environment defined in the APIM infrastructure repo and is not really being used by the team. However, the environment needs to exist for INT deployments to take place.
Refer to https://nhsd-jira.digital.nhs.uk/browse/EM-417 for more detail.
=> [EM-417] Disabled internal-qa tests

manifest_template.yml
Modifying the rate limiting config in line with our predicted workload. To be continually reviewed as the project progresses.
=> Rate Limiting Config

manifest_template.yml
=> Increasing rate limits

specification/multicast-notification-service.yaml
Changed event structure link to point to the new location.
=> [EM-433] Update event structure link

specification/components/schemas/pdsEventData.yaml, specification/multicast-notification-service.yaml, tests/data/pds-change-of-gp-event-mds.json
See ticket EM-560 for background on the ticket. Basically it's required for some of the logic that Notify a Patient needs to apply.
Could I request a good check of the wording? I know it's essentially Spine-specific as they are the only ones who will publish the PDS-triggered events, but it'd still be nice for it to be clear since it's going to be out there in the ether.
**NOTE:**
Tests will fail until the backend PR is merged: https://github.com/NHSDigital/event-pattern-poc/pull/443
=> EM-560 Add GP registration type/code to the specification

package-lock.json, tests/data/pds-change-of-gp-event-mds.json
Simple dependency bump from Dependabot. Had postponed it last time, due to the infrastructure PRs we were waiting on.
Creating a fresh PR as the old one was from a long-lived branch. Not sure how the APIM internal pipelines work, but could be something affecting it.
=> Bump Semver

pyproject.toml, specification/multicast-notification-service.yaml
See https://github.com/NHSDigital/multicast-notification-service-infrastructure/pull/572 this brings the description into line with the latest changes,
=> EM-645 Made update to datetime description in specification

specification/components/schemas/pdsEventData.yaml
Made `registrationEncounterCode` optional and added the expected pattern to `versionId ` description.
* [] Dev
=> EM-645 Made registrationEncounterCode optional

manifest_template.yml
See https://nhsd-jira.digital.nhs.uk/browse/EM-661 for more info.
=> EM-661 Update values

postman/sandbox/Multicast_Notification_Sandbox.postman_collection.json, sandbox/app.js, sandbox/app.spec.js, sandbox/handlers.js, specification/multicast-notification-service.yaml
Delete subscriptions endpoint.
Please **do not merge** until the backend ticket is complete or the error messages, HTTP response and so on are locked it!
=> EM-515 Added new endpoint for delete subscriptions

postman/sandbox/Multicast Notification Sandbox.postman_collection.json, sandbox/app.js, sandbox/app.spec.js, sandbox/handlers.js, specification/components/errors/internal-error.yaml, specification/components/errors/not-found-error.yaml, specification/components/errors/unauthenticated-error.yaml, specification/components/errors/unauthorised-error.yaml, specification/multicast-notification-service.yaml
Get me a list of all my subscriptions please, butler!
This PR also added some tidy refactoring
1. More descriptive sandbox tests by splitting up with describe blocks.
2. Consolidated shared OAS yaml into folders and used refs instead of duplicating it through the file.
=> EM-516 Added get ALL subscriptions docs

specification/multicast-notification-service.yaml
=> EM-772 Update API status to beta

specification/multicast-notification-service.yaml
As mentioned in the support channel, "Open source" is now a mandatory section in an APIM schema. All links in the PR should work, except the last one - you might need to check! I can see it because I created it, but the feature upvote is still being reviewed, so it might not be public yet.
=> EM-765 Add open source section to specification

manifest_template.yml
See ticket EM-767 for the analysis and reasoning for the update: https://nhsd-jira.digital.nhs.uk/browse/EM-767
=> EM-767 Update rate limits

postman/sandbox/Multicast Notification Sandbox.postman_collection.json, specification/components/schemas/cloudevents/nhsNumberChangeEventData.yaml, specification/components/schemas/cloudevents/nhsNumberChangeSignal.yaml, specification/multicast-notification-service.yaml, tests/data/nhs-number-change-event-mds.json, tests/test_endpoints.py
=> EM-733. Added NHS nunber change event/signal.

specification/multicast-notification-service.yaml
=> EM-810 Add NHS Number Change events to developer docs

specification/multicast-notification-service.yaml
=> EM-824 Add PDS Death Notification events to developer docs

specification/multicast-notification-service.yaml
Simple change to signpost that MESH delivery is available in addition to SQS. Please review the content thoroughly. Do we think we should also signpost this earlier in the description?
=> EM-830 Added description for mesh endpoint delivery

specification/multicast-notification-service.yaml
=> EM-802. Conflicting endpoint docs

specification/components/schemas/cloudevents/pdsChangeOfGpEventData.yaml, specification/components/schemas/cloudevents/pdsChangeOfGpSignal.yaml
Made the documentation around blank scenarios clearer for both the /publish event API documentation and the Signal which the Signal catalogue links to.
=> EM-902 Updated reg encounter code documentation

specification/components/schemas/cloudevents/nhsNumberChangeSignal.yaml, specification/components/schemas/cloudevents/pdsChangeOfGpSignal.yaml, specification/components/schemas/cloudevents/pdsDeathSignal.yaml
=> removed age field throughout repo

.github/dependabot.yml
=> EM-88. Switch to weekly schedule.

.github/workflows/scheduled-combine-dependabot-prs.yaml
=> EM-88. Added config for Dependabot combine action.

.github/workflows/scheduled-combine-dependabot-prs.yaml, tests/test_endpoints.py
=> EM-88. Add a retry delay for smoke tests.

specification/components/schemas/cloudevents/examples/gpregChangeGpRequestSignal.json, specification/components/schemas/cloudevents/gpregChangeGpRequestSignal.yaml
Using `pdsFullUrl` would have meant quite a few code changes that will possibly be unnecessary or have to be rolled back
=> Updated the schema for first/mvp implementation on MNS

specification/components/schemas/cloudevents/baseMnsCloudEventSignal.yaml, specification/components/schemas/cloudevents/examples/baseMnsCloudEventSignal.json, specification/components/schemas/cloudevents/examples/gpregChangeGpRequestSignal.json
=> New CloudEvent signal format base specification and gp reg specific one

specification/components/schemas/cloudevents/baseMnsCloudEventSignal.yaml, specification/components/schemas/cloudevents/gpregChangeGpRequestSignal.yaml
=> Make the types non nullable

signal-schemas/examples/gpreg-change-gp-req-1/hydrated-signal.json, signal-schemas/examples/gpreg-change-gp-req-1/signal.json, signal-schemas/fhirsignal.schema.json, signal-schemas/fhirsignal.schema.json.yaml
=> EM-0000 Update GP reg example

specification/components/schemas/cloudevents/examples/gpregChangeGpRequestSignal.json, specification/components/schemas/cloudevents/gpregChangeGpRequestSignal.yaml
=> EM-0000 Update missing gp reg url

specification/components/schemas/cloudevents/baseMnsCloudEventSignal.yaml, specification/components/schemas/fhir/R4/Subscription.yaml, specification/components/schemas/filtering/gpreg-change-gp-req-1-filtering.yaml, specification/multicast-notification-service.yaml
=> EM-1156 Update publish events schema

specification/multicast-notification-service.yaml
=> EM-0000 Fix generalpractice typo

specification/multicast-notification-service.yaml
=> EM-1137 Remove patient.identitfier filtering references

specification/multicast-notification-service.yaml
=> EM-1216 Highlight content-type required header for POST events

specification/multicast-notification-service.yaml
=> EM-0000 Add product owner overview updates

specification/components/schemas/filtering/gpreg-change-gp-req-1-filtering.yaml, specification/multicast-notification-service.yaml
=> EM-1139: GP Reg filtering

specification/multicast-notification-service.yaml
reopened from: https://github.com/NHSDigital/multicast-notification-service/pull/239
as the azure pipeline wasn't created correctly
=> em-1212: adding mesh url scheme support

specification/multicast-notification-service.yaml
Fixes a couple of instances of left + right quotes which don't work properly in a browser.
https://nhsd-jira.digital.nhs.uk/browse/EM-1380
=> em-1380: fix left and right quotes in spec

signal-schemas/patientflags-change-1/signal.json, specification/components/schemas/cloudevents/examples/patientflagsChangeSignal.json, specification/components/schemas/cloudevents/patientflagsChangeSignal.yaml, specification/components/schemas/filtering/patientflags-change-1-filtering.yaml, specification/multicast-notification-service.yaml
=> EM-1332 Add patientflags

specification/multicast-notification-service.yaml
=> EM-1332 Add patientflags to schema

azure/azure-release-pipeline.yml, manifest_template.yml
=> EM-1514 Add back in internal-qa and internal-qa-sandbox

azure/azure-release-pipeline.yml
=> EM-1514 Fix sandbox command

azure/azure-release-pipeline.yml
=> EM-1514 Pass app id for sandbox

azure/azure-release-pipeline.yml
=> EM-1514 Supply correct test apps for prod envs

proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml, sandbox/app.js, sandbox/package-lock.json, sandbox/package.json
=> EM-1609 Add cors to sandbox

specification/multicast-notification-service.yaml, specification/schemas/filtering/patientflags-change-1-filtering.yaml
=> EM-1631 Update filtering schema for patient flags to include origin

proxies/live/apiproxy/targets/target.xml
=> EM-0000 Reduct proxy keepalive

proxies/live/apiproxy/policies/AssignMessage.AddXAmznRequestIdHeader.xml, proxies/live/apiproxy/targets/target.xml, tests/test_endpoints.py
=> EM-982 Send through amazon request id header to the backend

.github/workflows/continuous-integration.yml
ERROR - https://github.com/NHSDigital/multicast-notification-service/actions/runs/16466133604/job/46543879179
FIX - https://github.com/actions/setup-python/issues/160
=> EM-310 Fix python version as int stopped release creation
